name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.3.27'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: |
          chmod -R 777 storage bootstrap/cache
          composer dump-autoload
          php artisan config:clear
          php artisan cache:clear
    - name: Run Testsuite
      run: php artisan test
    - name: Execute command for PHPCS
      run: vendor/bin/phpcs
    - name: Execute Command for PHPStan
      run: vendor/bin/phpstan analyse --memory-limit=2G
